# Custom Language File for Launcher Customizer

[ejs.app]
title = "Artenia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/LoenTm/ArteniaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/4w883Ecd"

[ejs.settings]
sourceGithubLink = "https://github.com/LoenTm/ArteniaLauncher"
supportLink = "https://github.com/LoenTm/ArteniaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Artenia"
welcomeDescription = "Artenia est un serveur SEMI-RP Cobblemon."
welcomeDescCTA = "Vous êtes à quelques clics d'Artenia!"
